import 'package:flutter/material.dart';

class AppStrings {
  final Locale locale;

  AppStrings(this.locale);

  static const supportedLocales = [Locale('en'), Locale('am')];

  static final Map<String, Map<String, String>> _values = {
    'en': _en,
    'am': _am,
  };

  String tr(String key, {Map<String, String> params = const {}}) {
    final map = _values[locale.languageCode] ?? _en;
    var value = map[key] ?? _en[key] ?? key;
    params.forEach((k, v) => value = value.replaceAll('{$k}', v));
    return value;
  }
}

extension AppStringsX on BuildContext {
  AppStrings get strings => AppStrings(Localizations.localeOf(this));
  String tr(String key, {Map<String, String> params = const {}}) =>
      strings.tr(key, params: params);
}

class AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const AppStringsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'am'].contains(locale.languageCode);

  @override
  Future<AppStrings> load(Locale locale) async {
    return AppStrings(locale);
  }

  @override
  bool shouldReload(AppStringsDelegate old) => false;
}

const Map<String, String> _en = {
  'app_name': 'Academic Collaboration',
  'start_subtitle': 'AN ASSIGNMENT HUB',
  'welcome_to': 'Welcome to',
  'get_started': 'Get Started',
  'start_tagline': 'Join collaborative classrooms',
  'start_description':
      'Assignments, group work, chat, and live calls in one polished academic workspace.',
  'secure_workspace': 'Secure workspace',
  'live_collaboration': 'Live collaboration',
  'agree_terms': 'By continuing, you agree to our Terms of Service.',
  'skip': 'Skip',
  'next': 'Next',
  'onboarding_title_1': 'Learn with your class, not around it',
  'onboarding_body_1':
      'Stay synced with lecturers, teammates, and assignments from the very first day.',
  'onboarding_title_2': 'Move at your pace',
  'onboarding_body_2':
      'Track deadlines, review resources, and keep momentum without losing the bigger picture.',
  'onboarding_title_3': 'Turn feedback into progress',
  'onboarding_body_3':
      'See updates, group activity, and live calls in one streamlined academic dashboard.',
  'support_message':
      'Need help? Contact our support team directly at support@educollab.com.',
  'splash_copy_1': 'Ideas come together.',
  'splash_copy_2': 'Connecting...',
  'splash_copy_3': 'Building together.',
  'splash_tagline': 'Learn together. Grow together.',
  'onboarding_badge_1': 'Daily progress',
  'onboarding_badge_2': 'Flexible pace',
  'onboarding_badge_3': 'Visible wins',
  'verification_step': 'Step 3 of 3',
  'verification_tip':
      'Enter the code from your inbox to finish setting up your account.',
  'open_assignments': 'Open assignments',
  'call_unavailable_short': 'Unable to open the call right now.',
  'login': 'Log In',
  'create_account': 'Create Account',
  'support': 'SUPPORT',
  'footer_credit': 'Created by AAiT Software Engineering students 2026',
  'language': 'Language',
  'english': 'English',
  'amharic': 'Amharic',
  'already_have_account': 'Already have an account? Login',
  'join_ecosystem': 'Join the intellectual curator ecosystem',
  'full_name': 'Full Name',
  'email_address': 'Email Address',
  'password': 'Password',
  'enter_full_name': 'Enter your full name',
  'email_hint': 'name@school.edu',
  'password_hint': '••••••••',
  'enter_required_fields': 'Enter a name, email, and a 6+ character password.',
  'creating': 'Creating...',
  'create': 'Create',
  'sign_in': 'Sign in to your studio',
  'sign_in_subtitle':
      'Track assignments, collaborate with your group, and submit with confidence.',
  'welcome_back': 'Welcome back',
  'welcome_back_name': 'Welcome back, {name}',
  'use_institution_credentials':
      'Use your institution credentials to continue.',
  'invalid_email_password':
      'Invalid email or password. Please check your information and try again.',
  'forgot_password': 'Forgot password?',
  'signing_in': 'Signing in...',
  'secure_access':
      'Secure access is protected with encrypted storage and session refresh.',
  'create_account_lower': 'Create account',
  'verify_email': 'Verify your email',
  'verify_email_subtitle': 'We sent a verification code to {email}.',
  'verify_email_no_email':
      'Start by creating an account to receive a verification code.',
  'verification_code': 'Verification Code',
  'enter_verification_code': 'Enter the verification code.',
  'code_hint': '6-digit code',
  'confirm_code': 'Confirm Code',
  'verifying': 'Verifying...',
  'invalid_or_expired_code': 'Invalid or expired code.',
  'forgot_password_title': 'Forgot your password?',
  'forgot_password_subtitle': 'We will email you a password reset link.',
  'send_reset_link': 'Send reset link',
  'sending': 'Sending...',
  'check_email_for_reset': 'Check your email for the reset link.',
  'reset_link_valid': 'Reset links are valid for 24 hours.',
  'home': 'Home',
  'good_morning': 'Good morning, {name}.',
  'assignments_due_this_week':
      'You have {count} assignments due this week. Let’s make progress.',
  'assignments_due': 'Assignments Due',
  'due_soon': 'Due Soon',
  'pending_submissions': 'Pending Submissions',
  'awaiting_review': 'Awaiting Review',
  'average_grade': 'Average Grade',
  'priority_focus': 'Priority focus',
  'upcoming_assignments': 'Upcoming Assignments',
  'view_all': 'View All',
  'assignments': 'Assignments',
  'stay_on_schedule': 'Stay on schedule',
  'your_assignments': 'Your assignments',
  'assignments_subtitle':
      'Track what is due, what is submitted, and what is complete across every course.',
  'filter': 'Filter',
  'sort_by_due_date': 'Sort by due date',
  'offline_cached_data': 'Offline: showing cached data',
  'no_assignments_yet': 'No assignments yet',
  'nothing_in_this_tab': 'Nothing in this tab',
  'upcoming_assignments_here': 'Upcoming assignments will show here.',
  'completed_assignments_here': 'Completed assignments will show here.',
  'assignments_synced_message':
      'Assignments appear after a lecturer assigns them to your email.',
  'due_date': 'Due {date}',
  'view_details': 'View details',
  'submit': 'Submit',
  'assignment_details': 'Assignment details',
  'sample_course_urban_design': 'Urban Design Studio III',
  'sample_assignment_title': 'Addis Ababa Urban Morphology Analysis',
  'attempts_left': '{count} attempts left',
  'not_graded': 'Not graded',
  'due_date_label': 'DUE DATE',
  'sample_due_datetime': 'Apr 24, 2026 • 11:59 PM',
  'assignment_brief': 'Assignment Brief',
  'view_rubric': 'View Rubric',
  'assignment_brief_body':
      'Develop a 12-page editorial layout that translates data from the "Addis Urbanization Report" into a clear narrative.',
  'solution_must_demonstrate': 'Your solution must demonstrate:',
  'bullet_multi_column': 'Multi-column grid systems',
  'bullet_vertical_rhythm': 'Consistent vertical rhythm',
  'bullet_contrast': 'Contrast through scale and weight',
  'bullet_micro_macro': 'Integration of micro and macro typography',
  'quote_breathing_room':
      '“Focus on the breathing room between data points. Clarity is the ultimate goal.” — Dr. Selamawit',
  'submission_status': 'SUBMISSION STATUS',
  'in_progress': 'In Progress',
  'attempts': 'Attempts',
  'grade': 'Grade',
  'submit_assignment': 'Submit Assignment',
  'unable_open_link': 'Unable to open the link.',
  'assignment_submission': 'Assignment Submission',
  'case_study_addis': 'Case Study: Addis Urbanism',
  'submission_instructions':
      'Please upload your final analysis and supporting diagrams. Ensure files meet the syllabus guidelines.',
  'submission_files': 'Submission Files',
  'max_file_size': 'MAX 50MB',
  'click_to_upload': 'Click to upload or drag and drop',
  'file_types_allowed': 'PDF, DOCX, or ZIP files only',
  'select_files': 'Select files',
  'submission_notes': 'Submission Notes',
  'submission_notes_hint':
      'Add any additional context for your instructor here...',
  'pre_submission_checklist': 'Pre-submission Checklist',
  'checklist_references': 'References are correctly cited using APA format.',
  'checklist_diagrams': 'All diagrams are high resolution (300dpi).',
  'checklist_filesize': 'File size is below the 50MB limit.',
  'checklist_incomplete':
      'One or more checklist items are incomplete. Please review before proceeding.',
  'quote_bibliographies':
      '“Double-check your bibliographies; these count for 15% of the grade.” — Dr. Selamawit',
  'retry': 'Retry',
  'submission_sent': 'Submission sent.',
  'uploading': 'Uploading...',
  'due_time': 'Due: {date}',
  'upload_failed': 'Upload failed. Check connection and retry.',
  'feedback_and_grade': 'Feedback & Grade',
  'grade_value': 'Grade: {value}',
  'sample_feedback_text':
      'Dr. Selamawit: Strong visual hierarchy and clear narrative flow. Tighten the data legend and cite sources on page 7.',
  'completed': 'Completed',
  'submitted': 'Submitted',
  'all': 'All',
  'upcoming': 'Upcoming',
  'resource_library': 'Resource Library',
  'resources': 'Resources',
  'resource_library_subtitle':
      'Access curated academic materials, course notes, and research papers to deepen your learning.',
  'search_resources': 'Search resources, topics, or keywords...',
  'offline_cached_resources': 'Offline mode: showing cached resources',
  'resources_unavailable': 'Resources unavailable',
  'no_resources_found': 'No resources found',
  'no_resources_subtitle':
      'Try a different filter or check back once new materials are added.',
  'downloaded': 'DOWNLOADED',
  'course_label': 'Course: {course}',
  'resource_size': '{type} • {size}',
  'open': 'Open',
  'offline': 'Offline',
  'chat': 'Chat',
  'all_courses': 'All Courses',
  'collaboration_hub': 'Collaboration Hub',
  'your_groups': 'Your Groups',
  'chat_server_url': 'Chat Server URL',
  'search_cohorts': 'Search cohorts or subjects...',
  'select_course': 'Select Course',
  'chat_unavailable': 'Chat unavailable',
  'chat_empty_subtitle':
      'Once you are assigned to a group, chats will appear here.',
  'chat_group_subtitle': '{course} • Studio',
  'chat_preview_sample': 'Mekdes: The draft is ready for review.',
  'minutes_ago': '{count}m ago',
  'open_chat': 'Open Chat',
  'chat_group_title_sample': 'Addis Heritage Studio',
  'chat_group_meta': '{course} • {members} members • {online} online',
  'schedule_meet_prompt':
      'Schedule a quick in-group meet to review today’s draft.',
  'schedule': 'Schedule',
  'join_call': 'Join Call',
  'type_message': 'Type a message...',
  'setup_meet': 'Setup In-group Meet',
  'topic': 'Topic',
  'date_time': 'Date & Time',
  'location_link': 'Location / Link',
  'cancel': 'Cancel',
  'group_meet': 'Group Meet',
  'study_room_link': 'Study Room / Meet Link',
  'notifications': 'Notifications',
  'notifications_unavailable': 'Notifications unavailable',
  'check_connection_try_again': 'Please check your connection and try again.',
  'no_notifications_yet': 'No notifications yet',
  'no_notifications_subtitle':
      'You are all caught up. New updates will appear here.',
  'today': 'Today',
  'hours_ago': '{count}h ago',
  'feedback': 'Feedback',
  'system': 'System',
  'individual_assignments': 'Individual Assignments',
  'assignments_unavailable': 'Assignments unavailable',
  'no_individual_assignments': 'No individual assignments',
  'no_individual_assignments_subtitle':
      'Create one to start collecting student submissions.',
  'group_assignments': 'Group Assignments',
  'no_group_assignments': 'No group assignments',
  'no_group_assignments_subtitle':
      'Group-based briefs will show here once created.',
  'academic_atelier': 'The Academic Atelier',
  'submissions': 'Submissions',
  'grade_all': 'Grade All',
  'submissions_unavailable': 'Submissions unavailable',
  'no_submissions_yet': 'No submissions yet',
  'no_submissions_subtitle':
      'Student submissions will appear here once they upload their work.',
  'grade_feedback': 'Grade & Feedback',
  'review_submission_for': 'Review submission for {name}',
  'historical_context': 'Historical Context',
  'critical_critique': 'Critical Critique',
  'visual_clarity': 'Visual Clarity',
  'lecturer_insight': 'Lecturer Insight',
  'save_draft': 'Save Draft',
  'submit_grade': 'Submit Grade',
  'assignments_new': 'Assignments > New Assignment',
  'curate_assignment': 'Curate an Assignment',
  'curate_assignment_subtitle':
      'Design a thoughtful task that encourages critical thinking and creative exploration.',
  'assignment_title': 'Assignment Title',
  'assignment_title_hint': 'e.g., Heritage Mapping: Addis Ababa',
  'assign_to_emails': 'Assign to student emails',
  'assign_to_emails_hint': 'student1@school.edu, student2@school.edu',
  'add_recipient_emails': 'Add at least one student email.',
  'assignment_type': 'Assignment Type',
  'individual_assignment': 'Individual',
  'group_assignment': 'Group',
  'group_assignment_note':
      'For group assignments, add all group member emails.',
  'start_group_call': 'Start Group Call',
  'starting_call': 'Starting call...',
  'call_student': 'Call student',
  'calls': 'Calls',
  'calls_subtitle':
      'See answered, missed, individual, and group call activity.',
  'all_calls': 'All calls',
  'answered_calls': 'Answered',
  'missed_calls': 'Missed',
  'all_call_types': 'All types',
  'individual_call': 'Individual call',
  'group_call': 'Group call',
  'missed_call': 'Missed',
  'answered_call': 'Answered',
  'call_logs_unavailable': 'Call history is unavailable right now.',
  'no_call_logs': 'No calls recorded yet.',
  'unknown_contact': 'Unknown contact',
  'video_call_unavailable': 'Video calling is unavailable right now.',
  'select_student_to_call':
      'Choose a student from submissions to start a call.',
  'opening_call': 'Opening call...',
  'send_email_notification': 'Send email notification',
  'send_email_notification_subtitle': 'Notify students when you publish.',
  'assigned_by_lecturer': 'Assigned by lecturer',
  'new_label': 'New',
  'new_items': '{count} new',
  'new_assignments_waiting': '{count} new assignments waiting',
  'no_group_emails_found': 'No group emails found. Add them manually.',
  'unable_load_group_emails': 'Unable to load group emails.',
  'add_member': 'Add member',
  'member_email_hint': 'student@school.edu',
  'enter_member_email': 'Enter a student email.',
  'member_added_email_sent': 'Member added. Email sent.',
  'member_added_email_failed': 'Member added, but email failed.',
  'member_add_failed': 'Unable to add member right now.',
  'member_remove_failed': 'Unable to remove member.',
  'remove_member': 'Remove member',
  'no_group_members': 'No members yet',
  'no_group_members_subtitle': 'Add students to start collaborating.',
  'unable_load_group_members': 'Unable to load group members.',
  'group_members': 'Group Members',
  'loading_group_emails': 'Loading group emails...',
  'resend_email': 'Resend email',
  'email_resend_success': 'Email sent.',
  'email_resend_failed': 'Email failed to send.',
  'email_sent_success': 'Email sent successfully.',
  'email_sent_failed': 'Email failed to send.',
  'group_invite_subject': 'Group invite',
  'search_members': 'Search members',
  'import_csv': 'Import CSV',
  'clear_search': 'Clear',
  'no_emails_found_csv': 'No emails found in CSV.',
  'csv_import_result': '{success} added • {failed} failed',
  'email_delivery_log': 'Email delivery log',
  'no_email_logs': 'No email activity yet.',
  'detailed_prompt': 'Detailed Prompt',
  'detailed_prompt_hint':
      'Describe the assignment goals and expected deliverables...',
  'course': 'Course',
  'due_date_field': 'Due Date',
  'attach_materials': 'Attach rubrics, readings, or templates',
  'publish_assignment': 'Publish Assignment',
  'fill_title_course': 'Please fill title and course.',
  'assignment_created': 'Assignment created.',
  'analytics': 'Analytics',
  'performance_review': 'Performance Review',
  'academic_growth': 'Your Academic Growth',
  'analytics_subtitle':
      'Track your theoretical assignments and studio hours to maintain a balanced creative rhythm.',
  'focus_hours': 'Focus Hours',
  'current_streak': 'Current Streak',
  'gpa_equivalent': 'GPA Equivalent',
  'weekly_progression': 'Weekly Progression',
  'vs_last_month': '{value} vs last month',
  'pending': 'Pending',
  'lecturer_analytics': 'Lecturer Analytics',
  'lecturer_analytics_subtitle': 'Overview of submissions and grading trends.',
  'submission_trends': 'Submission Trends',
  'on_time_rate': '{value} on-time',
  'feedback_turnaround': 'Feedback Turnaround',
  'days_value': '{value} days',
  'resource_details': 'Resource details',
  'academic_resource': 'ACADEMIC RESOURCE',
  'core_reading': 'CORE READING',
  'resource_title_sample': 'Lalibela Rock-Hewn Churches: Volume II',
  'heritage_conservation': 'Heritage Conservation',
  'academic_year_sample': 'Academic Year 2023-24',
  'pages_count': '{count} Pages',
  'available_offline': 'Available Offline',
  'download': 'Download',
  'page_of': 'Page {page} / {total}',
  'pdf_viewer_placeholder': 'PDF Viewer Placeholder',
  'resource_card': '{course} • {type}',
  'open_library': 'Open Library',
  'schedule_session': 'Schedule Session',
  'take_notes': 'Take Notes',
  'study_group': 'Study Group',
  'bookmarks': 'Bookmarks',
  'starts_in': 'Starts In',
  'assignment_due': '{course} • Due {date}',
  'profile': 'Profile',
  'profile_settings': 'Profile Settings',
  'groups': 'Groups',
  'groups_created_by_lecturer': 'Groups are created by lecturers',
  'groups_created_by_lecturer_subtitle':
      'Your lecturer will invite you to a group when it is ready.',
  'academic_collaboration': 'Academic Collaboration',
  'group_work_overview': 'Group Work Overview',
  'groups_overview': 'Groups Overview',
  'groups_overview_subtitle': 'Monitor collaboration health and milestones.',
  'manage_groups': 'Manage Groups',
  'group_management': 'Group Management',
  'group_management_subtitle':
      'Monitor contributions and catch free riders early.',
  'select_group': 'Select Group',
  'group_option': '{course} • {name}',
  'member_commits_activity': 'Member Commits & Activity',
  'anonymous_tips': 'Anonymous Tips',
  'free_rider_signals': 'Free-Rider Signals',
  'low_commit_count': 'Low commit count',
  'below_commits': 'Below {count} commits this week',
  'missed_meetings': 'Missed meetings',
  'attendance_below': 'Attendance below {percent}',
  'low_chat_activity': 'Low chat activity',
  'fewer_messages': 'Fewer than {count} messages',
  'late_task_delivery': 'Late task delivery',
  'tasks_overdue': '{count} tasks overdue',
  'request_checkin': 'Request Check-in',
  'flag_for_review': 'Flag For Review',
  'course_members': '{course} • {count} members',
  'member_stats': 'Commits: {commits} • Tasks: {tasks} • Msgs: {messages}',
  'attendance': 'Attendance {value}',
  'last_active': 'Last: {value}',
  'nothing_here_yet': 'Nothing here yet',
  'no_records_found':
      'We could not find any records for this view. Try refreshing or adjusting your filters.',
  'no_data_available': 'No data available',
  'content_will_appear':
      'Your content will appear here once new items are created.',
  'refresh': 'Refresh',
  'create_group': 'Create Group',
  'group_created': 'Group created successfully.',
  'groups_unavailable': 'Groups unavailable',
  'no_groups_yet': 'No groups yet',
  'no_groups_subtitle':
      'Create a group or wait for your instructor to assign one.',
  'members_count': '{count} members',
  'group_course_subtitle': '{course} • Collaborative studio work',
  'active_members': 'Active Members',
  'current_progress': 'Current Progress',
  'open_group': 'Open Group',
  'group_details': 'Group details',
  'project_abay_semester': 'PROJECT ABAY • SEMESTER II',
  'group_title_sample': 'Addis Heritage Narrative & Modernity',
  'group_detail_subtitle':
      'A collaborative exploration of 20th-century urbanism. Track milestones, contributions, and breakthroughs.',
  'active_collaborators': '{count} Active Collaborators',
  'milestone_progress': 'Milestone Progress',
  'phase1_research': 'Phase 1: Research Gathering',
  'completed_sept_12': 'Completed Sept 12',
  'phase2_drafting': 'Phase 2: Drafting & Review',
  'in_progress_tasks_left': 'In progress • {count} tasks left',
  'contribution_summary': 'Contribution Summary',
  'documentation': 'Documentation',
  'design_assets': 'Design Assets',
  'peer_review': 'Peer Review',
  'view_contributions': 'View Contributions',
  'create_group_subtitle': 'Set up a new collaboration space for your course.',
  'group_name': 'Group Name',
  'group_name_hint': 'Addis Heritage Studio',
  'student_name': 'Student Name',
  'student_name_hint': 'Dawit Bekele',
  'student_id': 'Student ID',
  'student_id_hint': 'AET/1245/16',
  'course_code': 'Course Code',
  'course_code_hint': 'ARCH-101',
  'description': 'Description',
  'group_description_hint': 'Short description of the group goals...',
  'architecture_student': 'Architecture Student',
  'semester_gpa': 'Semester GPA',
  'upcoming_milestone': 'Upcoming Milestone',
  'account_settings': 'Account Settings',
  'change_password': 'Change Password',
  'notification_preferences': 'Notification Preferences',
  'course_updates': 'Course Updates',
  'atelier_announcements': 'Atelier Announcements',
  'offline_mode_demo': 'Offline Mode (Demo)',
  'logout': 'Logout',
  'dashboard': 'Dashboard',
  'create_assignment': 'Create Assignment',
  'recent_submissions': 'Recent Submissions',
  'lecturer_dashboard_subtitle':
      'Cultivating intellectual curiosity across three active disciplines.',
  'active_courses': 'Active Courses',
  'pending_feedback': 'Pending Feedback',
  'pending_grading': 'Pending Grading',
  'avg_feedback_time': 'Avg. Feedback Time',
  'architecture_studio': 'Architecture Studio',
  'urban_morphology': 'Urban Morphology',
  'feedback_waiting': '{count} submissions waiting for feedback',
  'critiques_due': '{count} studio critiques due',
  'grading_pending': '{count} submissions awaiting grades',
  'rubric_review': '{count} rubric checks remaining',
  'avg_feedback_detail': 'Average feedback time: {value} days',
  'fastest_turnaround': 'Fastest turnaround: {value} days',
  'slowest_turnaround': 'Slowest turnaround: {value} days',
  'tap_for_details': 'Tap for details',
  'learning_signal': 'Learning Signal',
  'focus_sessions': 'Focus Sessions',
  'analytics_signal_subtitle':
      'Real-time learning velocity based on your latest sessions.',
  'this_week': 'This week',
  'flow_score': 'Flow Score',
  'teaching_signal': 'Teaching Signal',
  'class_pulse': 'Class Pulse Overview',
  'analytics_signal_lecturer_subtitle':
      'Live course activity blended across your active studios.',
  'on_time': 'On-time',
  'avg_grade': 'Avg. Grade',
  'feedback_speed': 'Feedback Speed',
  'meeting_logs': 'Meeting Logs',
  'attendance_dashboard': 'Attendance Dashboard',
  'attendance_dashboard_subtitle':
      'Track live sessions and attendance across groups.',
  'meeting_logs_unavailable': 'Meeting logs are unavailable right now.',
  'no_meeting_logs': 'No meeting sessions have been recorded yet.',
  'total_sessions': 'Total Sessions',
  'total_attendees': 'Total Attendees',
  'avg_session_duration': 'Avg. Session Duration',
  'group_id_label': 'Group {id}',
  'meeting_room_label': 'Room {room}',
  'attendees_count': '{count} attendees',
  'avg_duration_label': 'Avg {value}',
  'session_started_at': 'Started {time}',
  'meeting_oversight': 'Meeting Oversight',
  'meeting_oversight_subtitle':
      'Review attendance, duration, and participation.',
  'view_logs': 'View Logs',
  'live_badge': 'LIVE',
  'session_details': 'Session Details',
  'session_duration': 'Session Duration',
  'attendance_log': 'Attendance Log',
  'participation_score': '{value}%',
  'member': 'Member',
  'active_call_badge': '{count} Active',
  'export_csv': 'Export CSV',
  'export_csv_hint': 'Generate a CSV of attendance logs for reporting.',
  'copy_csv_hint': 'Copy the CSV below and save it to a file.',
  'days': 'days',
  'faculty_profile': 'Faculty Profile',
  'manage_teaching_preferences':
      'Manage your teaching preferences and profile.',
  'senior_faculty': 'Senior Faculty',
  'course_management': 'Course Management',
  'active_courses_label': 'Active Courses',
  'groups_assigned': 'Groups Assigned',
  'students': 'Students',
  'grading_preferences': 'Grading Preferences',
  'rubrics': 'Rubrics',
  'feedback_templates': 'Feedback Templates',
  'final_thesis_proposal': 'Final Thesis Proposal',
  'last_updated_months': 'Last updated {count} months ago',
  'course_updates_subtitle': 'New material, assignment changes',
  'atelier_announcements_subtitle': 'Studio-wide news and events',
};

const Map<String, String> _am = {
  'app_name': 'የትምህርት ትብብር',
  'start_subtitle': 'የተግባር ማዕከል',
  'welcome_to': 'እንኳን ወደ',
  'get_started': 'ጀምር',
  'start_tagline': 'የተባበሩ ክፍሎችን ይቀላቀሉ',
  'start_description':
      'ተግባራት፣ የቡድን ስራ፣ ቻት እና የቀጥታ ጥሪዎችን በአንድ ዘመናዊ የትምህርት ስርዓት ውስጥ ያግኙ።',
  'secure_workspace': 'ደህንነቱ የተጠበቀ ቦታ',
  'live_collaboration': 'የቀጥታ ትብብር',
  'agree_terms': 'በመቀጠል የአገልግሎት ውሎቻችንን ተስማምተዋል።',
  'skip': 'ዝለል',
  'next': 'ቀጣይ',
  'onboarding_title_1': 'ከክፍልዎ ጋር በአንድነት ይማሩ',
  'onboarding_body_1':
      'ከመጀመሪያው ቀን ጀምሮ ከአስተማሪዎች፣ ከቡድን አባላት እና ከተግባራት ጋር ተመሳሳይ መረጃ ይኑርዎት።',
  'onboarding_title_2': 'በራስዎ ፍጥነት ይጓዙ',
  'onboarding_body_2':
      'ጊዜ ገደቦችን ይከታተሉ፣ ምንጮችን ይመልከቱ፣ እና ትልቁን ምስል ሳያጡ እድገትዎን ይጠብቁ።',
  'onboarding_title_3': 'ግብረመልስን ወደ እድገት ይቀይሩ',
  'onboarding_body_3':
      'ማሻሻያዎችን፣ የቡድን እንቅስቃሴን እና የቀጥታ ጥሪዎችን በአንድ የተዘጋጀ የትምህርት መቆጣጠሪያ ውስጥ ይመልከቱ።',
  'support_message': 'እርዳታ ይፈልጋሉ? በ support@educollab.com የድጋፍ ቡድናችንን ያግኙ።',
  'splash_copy_1': 'ሀሳቦች አንድ ይሆናሉ።',
  'splash_copy_2': 'በመገናኘት ላይ...',
  'splash_copy_3': 'በአንድነት በመገንባት ላይ።',
  'splash_tagline': 'በአንድነት ተማሩ። በአንድነት እደጉ።',
  'onboarding_badge_1': 'ዕለታዊ እድገት',
  'onboarding_badge_2': 'ተለዋዋጭ ፍጥነት',
  'onboarding_badge_3': 'የሚታዩ ውጤቶች',
  'verification_step': 'ደረጃ 3 ከ 3',
  'verification_tip': 'መለያዎን ለመጨረስ ከኢሜይልዎ የመጣውን ኮድ ያስገቡ።',
  'open_assignments': 'ተግባራትን ክፈት',
  'call_unavailable_short': 'ጥሪውን አሁን መክፈት አልተቻለም።',
  'login': 'ግባ',
  'create_account': 'መለያ ፍጠር',
  'support': 'ድጋፍ',
  'footer_credit': 'በAAiT ሶፍትዌር ኢንጂነሪንግ ተማሪዎች 2026 የተፈጠረ',
  'language': 'ቋንቋ',
  'english': 'English',
  'amharic': 'አማርኛ',
  'already_have_account': 'መለያ ካለዎት ግባ',
  'join_ecosystem': 'የአካዳሚክ ማህበር ተቀላቀሉ',
  'full_name': 'ሙሉ ስም',
  'email_address': 'ኢሜይል አድራሻ',
  'password': 'የይለፍ ቃል',
  'enter_full_name': 'ሙሉ ስምዎን ያስገቡ',
  'email_hint': 'name@school.edu',
  'password_hint': '••••••••',
  'enter_required_fields': 'ስም፣ ኢሜይል እና 6+ ቁምፊ ያለው የይለፍ ቃል ያስገቡ።',
  'creating': 'በመፍጠር ላይ...',
  'create': 'ፍጠር',
  'sign_in': 'ወደ ስቱዲዮዎ ግቡ',
  'sign_in_subtitle': 'ተግባራትን ይከታተሉ፣ ከቡድንዎ ጋር ተባብሩ፣ በመተማመን ያስገቡ።',
  'welcome_back': 'እንኳን ደህና መጡ',
  'welcome_back_name': 'እንኳን ደህና መጡ፣ {name}',
  'use_institution_credentials': 'የትምህርት ተቋም መለያዎን ይጠቀሙ።',
  'invalid_email_password': 'ትክክለኛ ኢሜይል ወይም የይለፍ ቃል አይደለም። ይሞክሩ።',
  'forgot_password': 'የይለፍ ቃል ረሱ?',
  'signing_in': 'በመግባት ላይ...',
  'secure_access': 'የደህንነት መዳረሻ በማስጠንቀቂያ ተጠብቋል።',
  'create_account_lower': 'መለያ ፍጠር',
  'verify_email': 'ኢሜይልዎን ያረጋግጡ',
  'verify_email_subtitle': 'የማረጋገጫ ኮድ ወደ {email} ተልኳል።',
  'verify_email_no_email': 'መለያ በመፍጠር ኮድ ይቀበሉ።',
  'verification_code': 'የማረጋገጫ ኮድ',
  'enter_verification_code': 'የማረጋገጫ ኮድ ያስገቡ።',
  'code_hint': '6 ቁጥር ኮድ',
  'confirm_code': 'ኮድ አረጋግጥ',
  'verifying': 'በማረጋገጥ ላይ...',
  'invalid_or_expired_code': 'ኮዱ ልክ አይደለም ወይም ጊዜው አልፎታል።',
  'forgot_password_title': 'የይለፍ ቃል ረሱ?',
  'forgot_password_subtitle': 'የይለፍ ቃል ማስተካከያ አገናኝ እንልካለን።',
  'send_reset_link': 'ማስተካከያ አገናኝ ላክ',
  'sending': 'በመላክ ላይ...',
  'check_email_for_reset': 'ማስተካከያ አገናኝ ለመረጃ ኢሜይልዎን ይመልከቱ።',
  'reset_link_valid': 'የማስተካከያ አገናኞች ለ24 ሰዓት ብቻ ይሰራሉ።',
  'home': 'ቤት',
  'good_morning': 'እንዴት ነው ፣ {name}.',
  'assignments_due_this_week': 'በዚህ ሳምንት {count} ተግባራት ይጠናቀቃሉ። እንቀጥል።',
  'assignments_due': 'የሚጠናቀቁ ተግባራት',
  'due_soon': 'ቀርቦ የሚጠናቀቅ',
  'pending_submissions': 'በመጠበቅ ላይ ያሉ ማስገባቶች',
  'awaiting_review': 'በግምገማ ላይ',
  'average_grade': 'አማካይ ውጤት',
  'priority_focus': 'የቅድሚያ ትኩረት',
  'upcoming_assignments': 'ቀረቡ ተግባራት',
  'view_all': 'ሁሉንም አሳይ',
  'assignments': 'ተግባራት',
  'stay_on_schedule': 'በጊዜ ላይ ቆዩ',
  'your_assignments': 'የእርስዎ ተግባራት',
  'assignments_subtitle': 'የሚጠናቀቁትን፣ የተገቡትን እና የተጠናቀቁትን በሁሉም ኮርሶች ላይ ይከታተሉ።',
  'filter': 'ማጣሪያ',
  'sort_by_due_date': 'በጊዜ መደርደር',
  'offline_cached_data': 'ከመስመር ውጭ፡ የተቀመጠ መረጃ',
  'no_assignments_yet': 'እስካሁን ተግባር የለም',
  'nothing_in_this_tab': 'በዚህ ትር ምንም የለም',
  'upcoming_assignments_here': 'ቀረቡ ተግባራት እዚህ ይታያሉ።',
  'completed_assignments_here': 'የተጠናቀቁ ተግባራት እዚህ ይታያሉ።',
  'assignments_synced_message': 'ተግባራት በአስተማሪዎ ወደ ኢሜይልዎ ከተመደቡ በኋላ ይታያሉ።',
  'due_date': 'የሚጠናቀቀበት {date}',
  'view_details': 'ዝርዝር ይመልከቱ',
  'submit': 'አስገባ',
  'assignment_details': 'የተግባር ዝርዝር',
  'sample_course_urban_design': 'የከተማ ዲዛይን ስቱዲዮ III',
  'sample_assignment_title': 'የአዲስ አበባ የከተማ አካል ትንተና',
  'attempts_left': '{count} ሙከራ ቀርቷል',
  'not_graded': 'አልተመዘነም',
  'due_date_label': 'የሚጠናቀቀበት ቀን',
  'sample_due_datetime': 'ኤፕሪል 24 2026 • 11:59 ማታ',
  'assignment_brief': 'የተግባር መግለጫ',
  'view_rubric': 'መመዘኛ አሳይ',
  'assignment_brief_body':
      'ከ"Addis Urbanization Report" ውስጥ ያለውን መረጃ ወደ ግልጽ ተረት የሚቀየር 12 ገፅ ኤዲቶሪያል አቀራረብ ያቀርቡ።',
  'solution_must_demonstrate': 'መፍትሄዎ ማሳየት ያለበት፡',
  'bullet_multi_column': 'ብዙ አምድ ግሪድ ስርዓት',
  'bullet_vertical_rhythm': 'ቋሚ ሪዝም ማስጠበቅ',
  'bullet_contrast': 'በመጠን እና ክብደት ንፅፅር',
  'bullet_micro_macro': 'ማይክሮ እና ማክሮ ታይፖግራፊ መዋሃድ',
  'quote_breathing_room':
      '“በዳታ ነጥቦች መካከል ያለውን ክፍተት ተጠብቁ። ግልጽነት ዋና ግብ ነው።” — ዶክተር ሰላማዊት',
  'submission_status': 'የማስገባት ሁኔታ',
  'in_progress': 'በሂደት ላይ',
  'attempts': 'ሙከራዎች',
  'grade': 'ውጤት',
  'submit_assignment': 'ተግባር አስገባ',
  'unable_open_link': 'አገናኙን ማስከፈት አልተቻለም።',
  'assignment_submission': 'የተግባር ማስገባት',
  'case_study_addis': 'የጉዳይ ጥናት፡ አዲስ ከተማነት',
  'submission_instructions':
      'የመጨረሻ ትንታኔዎን እና የሚደግፉ ዲያግራሞችን ያስገቡ። ፋይሎች የሲላበስ መመሪያን መተከል አለባቸው።',
  'submission_files': 'የማስገባት ፋይሎች',
  'max_file_size': 'ከፍተኛ 50MB',
  'click_to_upload': 'ለመስቀል ጠቅ ያድርጉ ወይም ይጎትቱ',
  'file_types_allowed': 'PDF፣ DOCX ወይም ZIP ብቻ',
  'select_files': 'ፋይሎች ምረጥ',
  'submission_notes': 'የማስገባት ማስታወሻ',
  'submission_notes_hint': 'ለአስተማሪዎ ተጨማሪ መረጃ እዚህ ያክሉ...',
  'pre_submission_checklist': 'ከማስገባት በፊት ዝርዝር',
  'checklist_references': 'ምንጮች በAPA ቅርጸት በትክክል ተጠቅሰዋል።',
  'checklist_diagrams': 'ሁሉም ዲያግራሞች ከፍተኛ ጥራት (300dpi) ናቸው።',
  'checklist_filesize': 'የፋይል መጠን ከ50MB በታች ነው።',
  'checklist_incomplete': 'አንዳንድ እቃዎች አልተሟሉም። ቀጥለው ከመሄድዎ በፊት ይመልከቱ።',
  'quote_bibliographies':
      '“ባይብሊዮግራፊዎችዎን እንደገና ያረጋግጡ፤ ይህ 15% ውጤት ያስከትላል።” — ዶክተር ሰላማዊት',
  'retry': 'ዳግም ሞክር',
  'submission_sent': 'ማስገባት ተልኳል።',
  'uploading': 'በመስቀል ላይ...',
  'due_time': 'መጨረሻ: {date}',
  'upload_failed': 'መስቀል አልተሳካም። እባክዎ ግንኙነት ያረጋግጡና ደግመው ይሞክሩ።',
  'feedback_and_grade': 'ግምገማ እና ውጤት',
  'grade_value': 'ውጤት፦ {value}',
  'sample_feedback_text':
      'ዶክተር ሰላማዊት፡ ግልጽ የዲዛይን ተርታ እና ተስማሚ ትርኢት። የዳታ ታሪክ ምልክትን ያስተካክሉ እና ምንጮችን በገፅ 7 ይጠቅሱ።',
  'completed': 'ተጠናቋል',
  'submitted': 'ተገብቷል',
  'all': 'ሁሉ',
  'upcoming': 'ቀረቡ',
  'resource_library': 'የምንጭ ቤት',
  'resources': 'ምንጮች',
  'resource_library_subtitle':
      'የተዘጋጁ የትምህርት ንብረቶች፣ የኮርስ ማስታወሻዎች እና የምርምር ጽሁፎችን ይድረሱ።',
  'search_resources': 'ምንጮችን፣ ርዕሶችን ወይም ቁልፍ ቃላትን ፈልግ...',
  'offline_cached_resources': 'ከመስመር ውጭ፡ የተቀመጡ ምንጮች ብቻ ይታያሉ',
  'resources_unavailable': 'ምንጮች አይገኙም',
  'no_resources_found': 'ምንጭ አልተገኘም',
  'no_resources_subtitle': 'ሌላ ማጣሪያ ይሞክሩ ወይም አዲስ ነገሮች እስኪመጡ ይጠብቁ።',
  'downloaded': 'ተወርዷል',
  'course_label': 'ኮርስ፡ {course}',
  'resource_size': '{type} • {size}',
  'open': 'ክፈት',
  'offline': 'ከመስመር ውጭ',
  'chat': 'ውይይት',
  'all_courses': 'ሁሉም ኮርሶች',
  'collaboration_hub': 'የትብብር ማዕከል',
  'your_groups': 'የእርስዎ ቡድኖች',
  'chat_server_url': 'የውይይት አገልጋይ URL',
  'search_cohorts': 'ቡድኖችን ወይም ርዕሶችን ፈልግ...',
  'select_course': 'ኮርስ ይምረጡ',
  'chat_unavailable': 'ውይይት አይገኝም',
  'chat_empty_subtitle': 'ወደ ቡድን ከተመደቡ በኋላ ውይይቶች እዚህ ይታያሉ።',
  'chat_group_subtitle': '{course} • ስቱዲዮ',
  'chat_preview_sample': 'መቅደስ፡ ረቂቁ ለግምገማ ዝግጁ ነው።',
  'minutes_ago': '{count} ደቂቃ በፊት',
  'open_chat': 'ውይይት ክፈት',
  'chat_group_title_sample': 'የአዲስ ቅርስ ስቱዲዮ',
  'chat_group_meta': '{course} • {members} አባላት • {online} መስመር ላይ',
  'schedule_meet_prompt': 'ዛሬዎቹን ረቂቆች ለመገምገም አጭር ስብሰባ ያስመዝግቡ።',
  'schedule': 'ቀጠሮ ያዝ',
  'join_call': 'ጥሪ ተቀላቀል',
  'type_message': 'መልዕክት ይጻፉ...',
  'setup_meet': 'የቡድን ስብሰባ ያዘጋጁ',
  'topic': 'ርዕስ',
  'date_time': 'ቀን እና ሰዓት',
  'location_link': 'ቦታ / ሊንክ',
  'cancel': 'ሰርዝ',
  'group_meet': 'የቡድን ስብሰባ',
  'study_room_link': 'የጥናት ክፍል / የስብሰባ ሊንክ',
  'notifications': 'ማስታወቂያዎች',
  'notifications_unavailable': 'ማስታወቂያዎች አይገኙም',
  'check_connection_try_again': 'እባክዎ ግንኙነትዎን ይመልከቱ እና ደግመው ይሞክሩ።',
  'no_notifications_yet': 'እስካሁን ማስታወቂያ የለም',
  'no_notifications_subtitle': 'አዲስ ማስታወቂያዎች እዚህ ይታያሉ።',
  'today': 'ዛሬ',
  'hours_ago': '{count} ሰዓት በፊት',
  'feedback': 'ግምገማ',
  'system': 'ስርዓት',
  'individual_assignments': 'የግል ተግባራት',
  'assignments_unavailable': 'ተግባራት አይገኙም',
  'no_individual_assignments': 'የግል ተግባር የለም',
  'no_individual_assignments_subtitle': 'ተግባር ፍጠሩ እና የተማሪ ማስገባቶችን ጀምሩ።',
  'group_assignments': 'የቡድን ተግባራት',
  'no_group_assignments': 'የቡድን ተግባር የለም',
  'no_group_assignments_subtitle': 'የቡድን ብሪፎች እዚህ ይታያሉ።',
  'academic_atelier': 'አካዳሚክ አቴሊየር',
  'submissions': 'ማስገባቶች',
  'grade_all': 'ሁሉን ውጤት ስጥ',
  'submissions_unavailable': 'ማስገባቶች አይገኙም',
  'no_submissions_yet': 'እስካሁን ማስገባት የለም',
  'no_submissions_subtitle': 'ተማሪዎች ሥራቸውን ካስገቡ በኋላ እዚህ ይታያሉ።',
  'grade_feedback': 'ውጤት እና ግምገማ',
  'review_submission_for': '{name} ለማስገባት ግምገማ',
  'historical_context': 'ታሪካዊ አውድ',
  'critical_critique': 'አስተያየት ግምገማ',
  'visual_clarity': 'የቪዥዋል ግልጽነት',
  'lecturer_insight': 'የአስተማሪ ምልከታ',
  'save_draft': 'ረቂቅ አስቀምጥ',
  'submit_grade': 'ውጤት አስገባ',
  'assignments_new': 'ተግባራት > አዲስ ተግባር',
  'curate_assignment': 'ተግባር ያዘጋጁ',
  'curate_assignment_subtitle': 'አስተያየትና ፈጠራ ለማበረታት ጥሩ ተግባር ያዘጋጁ።',
  'assignment_title': 'የተግባር ርዕስ',
  'assignment_title_hint': 'ለምሳሌ፡ የቅርስ ካርታ ስራ: አዲስ አበባ',
  'assign_to_emails': 'ለተማሪ ኢሜይሎች መመደብ',
  'assign_to_emails_hint': 'student1@school.edu, student2@school.edu',
  'add_recipient_emails': 'ቢያንስ አንድ የተማሪ ኢሜይል ያክሉ።',
  'assignment_type': 'የተግባር አይነት',
  'individual_assignment': 'ግለሰብ',
  'group_assignment': 'ቡድን',
  'group_assignment_note': 'ለቡድን ተግባር የቡድኑን ኢሜይሎች ሁሉ ያክሉ።',
  'start_group_call': 'የቡድን ጥሪ ጀምር',
  'starting_call': 'ጥሪ በመጀመር ላይ...',
  'call_student': 'ተማሪን ደውል',
  'calls': 'ጥሪዎች',
  'calls_subtitle': 'የተመለሱ፣ ያልተመለሱ፣ የግል እና የቡድን ጥሪዎችን ይመልከቱ።',
  'all_calls': 'ሁሉም ጥሪዎች',
  'answered_calls': 'የተመለሱ',
  'missed_calls': 'ያልተመለሱ',
  'all_call_types': 'ሁሉም አይነቶች',
  'individual_call': 'የግል ጥሪ',
  'group_call': 'የቡድን ጥሪ',
  'missed_call': 'ያልተመለሰ',
  'answered_call': 'የተመለሰ',
  'call_logs_unavailable': 'የጥሪ ታሪክ አሁን አይገኝም።',
  'no_call_logs': 'እስካሁን የተመዘገበ ጥሪ የለም።',
  'unknown_contact': 'ያልታወቀ ግንኙነት',
  'video_call_unavailable': 'የቪዲዮ ጥሪ አሁን አይገኝም።',
  'select_student_to_call': 'ጥሪ ለመጀመር ከማስገባቶች ውስጥ ተማሪ ይምረጡ።',
  'opening_call': 'ጥሪ በመክፈት ላይ...',
  'send_email_notification': 'የኢሜይል ማሳወቂያ ላክ',
  'send_email_notification_subtitle': 'በሚታተሙ ጊዜ ተማሪዎችን ያሳውቁ።',
  'assigned_by_lecturer': 'በአስተማሪ ተመድቧል',
  'new_label': 'አዲስ',
  'new_items': '{count} አዲስ',
  'new_assignments_waiting': '{count} አዲስ ተግባሮች ተጠባቂ ናቸው',
  'no_group_emails_found': 'የቡድን ኢሜይሎች አልተገኙም። በእጅ ያክሉ።',
  'unable_load_group_emails': 'የቡድን ኢሜይሎችን ማምጣት አልተቻለም።',
  'add_member': 'አባል ጨምር',
  'member_email_hint': 'student@school.edu',
  'enter_member_email': 'የተማሪ ኢሜይል ያስገቡ።',
  'member_added_email_sent': 'አባል ታክሏል። ኢሜይል ተልኳል።',
  'member_added_email_failed': 'አባል ታክሏል፣ ነገር ግን ኢሜይል አልተላከም።',
  'member_add_failed': 'አባል መጨመር አልተቻለም።',
  'member_remove_failed': 'አባል ማስወገድ አልተቻለም።',
  'remove_member': 'አባል አስወግድ',
  'no_group_members': 'እስካሁን አባል የለም',
  'no_group_members_subtitle': 'ለመጀመር ተማሪዎችን ያክሉ።',
  'unable_load_group_members': 'የቡድን አባላትን ማምጣት አልተቻለም።',
  'group_members': 'የቡድን አባላት',
  'loading_group_emails': 'የቡድን ኢሜይሎች በመጫን ላይ...',
  'resend_email': 'ኢሜይል ዳግመኛ ላክ',
  'email_resend_success': 'ኢሜይል ተልኳል።',
  'email_resend_failed': 'ኢሜይል ላክ አልተሳካም።',
  'email_sent_success': 'ኢሜይል በተሳካ ሁኔታ ተልኳል።',
  'email_sent_failed': 'ኢሜይል መላክ አልተሳካም።',
  'group_invite_subject': 'የቡድን ግብዣ',
  'search_members': 'አባላትን ፈልግ',
  'import_csv': 'CSV አስመጣ',
  'clear_search': 'አጥፋ',
  'no_emails_found_csv': 'በCSV ውስጥ ኢሜይል አልተገኘም።',
  'csv_import_result': '{success} ታክሏል • {failed} አልተሳካም',
  'email_delivery_log': 'የኢሜይል የመድረስ መዝገብ',
  'no_email_logs': 'እስካሁን የኢሜይል እንቅስቃሴ የለም።',
  'detailed_prompt': 'ዝርዝር መመሪያ',
  'detailed_prompt_hint': 'የተግባሩን ግብ እና የሚፈለጉ ማቅረቦችን ይግለጹ...',
  'course': 'ኮርስ',
  'due_date_field': 'የሚጠናቀቀበት ቀን',
  'attach_materials': 'መመዘኛዎችን፣ ንባብ ወይም አብነቶችን ያክሉ',
  'publish_assignment': 'ተግባር አትም',
  'fill_title_course': 'እባክዎ ርዕስና ኮርስ ያስገቡ።',
  'assignment_created': 'ተግባር ተፈጥሯል።',
  'analytics': 'ትንታኔ',
  'performance_review': 'የአፈጻጸም ግምገማ',
  'academic_growth': 'የትምህርት እድገትዎ',
  'analytics_subtitle': 'የንድፈ ትምህርት ተግባራትን እና የስቱዲዮ ሰዓታትን ተከታትሉ።',
  'focus_hours': 'የትኩረት ሰዓታት',
  'current_streak': 'አሁን ያለ ቀጣይ ቀናት',
  'gpa_equivalent': 'GPA ተመሳሳይ',
  'weekly_progression': 'የሳምንት እድገት',
  'vs_last_month': '{value} ከባለፈው ወር ጋር',
  'pending': 'በመጠበቅ ላይ',
  'lecturer_analytics': 'የአስተማሪ ትንታኔ',
  'lecturer_analytics_subtitle': 'የማስገባቶች እና የመመዘኛ አዝማሚያዎች እይታ።',
  'submission_trends': 'የማስገባት አዝማሚያ',
  'on_time_rate': '{value} በጊዜ ላይ',
  'feedback_turnaround': 'የግምገማ ቀጠሮ',
  'days_value': '{value} ቀናት',
  'resource_details': 'የምንጭ ዝርዝር',
  'academic_resource': 'የትምህርት ምንጭ',
  'core_reading': 'ዋና ንባብ',
  'resource_title_sample': 'የላሊበላ ድንጋይ ቤተክርስቲያኖች፡ ጥራዝ II',
  'heritage_conservation': 'የቅርስ ጥበቃ',
  'academic_year_sample': 'የትምህርት ዓመት 2023-24',
  'pages_count': '{count} ገፆች',
  'available_offline': 'ከመስመር ውጭ ይገኛል',
  'download': 'አውርድ',
  'page_of': 'ገፅ {page} / {total}',
  'pdf_viewer_placeholder': 'የPDF ተመልካች ቦታ',
  'resource_card': '{course} • {type}',
  'open_library': 'ቤተ-ምንጭ ክፈት',
  'schedule_session': 'ቀጠሮ ያዘጋጁ',
  'take_notes': 'ማስታወሻ ይያዙ',
  'study_group': 'የጥናት ቡድን',
  'bookmarks': 'ምልክቶች',
  'starts_in': 'ጀምሮ ውስጥ',
  'assignment_due': '{course} • የሚጠናቀቀበት {date}',
  'profile': 'መገለጫ',
  'profile_settings': 'የመገለጫ ቅንብሮች',
  'groups': 'ቡድኖች',
  'groups_created_by_lecturer': 'ቡድኖች በአስተማሪዎች ይፈጠራሉ',
  'groups_created_by_lecturer_subtitle': 'አስተማሪዎ ቡድኑ ሲዘጋጅ ግብዣ ይልካል።',
  'academic_collaboration': 'የትምህርት ትብብር',
  'group_work_overview': 'የቡድን ስራ አጠቃላይ እይታ',
  'groups_overview': 'የቡድን አጠቃላይ እይታ',
  'groups_overview_subtitle': 'የትብብር ጤናና መለኪያዎችን ተከታትሉ።',
  'manage_groups': 'ቡድኖችን አስተዳድር',
  'group_management': 'የቡድን አስተዳደር',
  'group_management_subtitle': 'አባልነትን ተከታትሉ እና ነፃ ተጠቃሚዎችን ቀድሞ ያስቀምጡ።',
  'select_group': 'ቡድን ይምረጡ',
  'group_option': '{course} • {name}',
  'member_commits_activity': 'የአባላት ኮሚትና እንቅስቃሴ',
  'anonymous_tips': 'የማይታወቁ ጥቆማዎች',
  'free_rider_signals': 'የነፃ ተጠቃሚ ምልክቶች',
  'low_commit_count': 'ዝቅተኛ ኮሚት ቁጥር',
  'below_commits': 'በዚህ ሳምንት {count} ኮሚት በታች',
  'missed_meetings': 'የተቀሩ ስብሰባዎች',
  'attendance_below': 'ተሳትፎ {percent} በታች',
  'low_chat_activity': 'ዝቅተኛ ውይይት እንቅስቃሴ',
  'fewer_messages': 'ከ{count} መልዕክቶች በታች',
  'late_task_delivery': 'የተዘገየ ስራ',
  'tasks_overdue': '{count} ስራዎች ዘግይተዋል',
  'request_checkin': 'መረጋገጫ ጠይቅ',
  'flag_for_review': 'ለግምገማ ምልክት አድርግ',
  'course_members': '{course} • {count} አባላት',
  'member_stats': 'ኮሚት፡ {commits} • ስራዎች፡ {tasks} • መልዕክቶች፡ {messages}',
  'attendance': 'ተሳትፎ {value}',
  'last_active': 'መጨረሻ፡ {value}',
  'nothing_here_yet': 'እስካሁን ምንም የለም',
  'no_records_found': 'በዚህ እይታ ምንም መዝገቦች አልተገኙም። እባክዎ ያድሱ ወይም ማጣሪያዎችን ያስተካክሉ።',
  'no_data_available': 'ምንም መረጃ የለም',
  'content_will_appear': 'አዲስ እቃዎች ከተፈጠሩ በኋላ ይታያሉ።',
  'refresh': 'አድስ',
  'create_group': 'ቡድን ፍጠር',
  'group_created': 'ቡድኑ በተሳካ ሁኔታ ተፈጠረ።',
  'groups_unavailable': 'ቡድኖች አይገኙም',
  'no_groups_yet': 'እስካሁን ቡድን የለም',
  'no_groups_subtitle': 'ቡድን ፍጠሩ ወይም ከአስተማሪዎ መመደብ ይጠብቁ።',
  'members_count': '{count} አባላት',
  'group_course_subtitle': '{course} • የትብብር ስራ',
  'active_members': 'ንቁ አባላት',
  'current_progress': 'አሁን ያለ ሂደት',
  'open_group': 'ቡድን ክፈት',
  'group_details': 'የቡድን ዝርዝር',
  'project_abay_semester': 'ፕሮጀክት አባይ • ሴሜስተር II',
  'group_title_sample': 'የአዲስ ቅርስ ትርኢት እና ዘመናዊነት',
  'group_detail_subtitle': 'የ20ኛው ክፍለ ዘመን ከተማነትን የሚመለከት ትብብራዊ ጥናት።',
  'active_collaborators': '{count} ንቁ ተባባሪዎች',
  'milestone_progress': 'የማስፈንጠሪያ ሂደት',
  'phase1_research': 'ክፍል 1፡ የምርምር ስብስብ',
  'completed_sept_12': 'መስከረም 12 ተጠናቋል',
  'phase2_drafting': 'ክፍል 2፡ ረቂቅ እና ግምገማ',
  'in_progress_tasks_left': 'በሂደት ላይ • {count} ተግባራት ቀሩ',
  'contribution_summary': 'የአባልነት ማጠቃለያ',
  'documentation': 'ሰነድ',
  'design_assets': 'የዲዛይን ንብረቶች',
  'peer_review': 'የተጓደኛ ግምገማ',
  'view_contributions': 'አባልነት አሳይ',
  'create_group_subtitle': 'ለኮርስዎ አዲስ የትብብር ቦታ ያቋቁሙ።',
  'group_name': 'የቡድን ስም',
  'group_name_hint': 'የአዲስ ቅርስ ስቱዲዮ',
  'student_name': 'የተማሪ ስም',
  'student_name_hint': 'ዳዊት በቀለ',
  'student_id': 'የተማሪ መለያ',
  'student_id_hint': 'AET/1245/16',
  'course_code': 'የኮርስ ኮድ',
  'course_code_hint': 'ARCH-101',
  'description': 'መግለጫ',
  'group_description_hint': 'የቡድን ግቦችን አጭር ይግለጹ...',
  'architecture_student': 'የስነ-ህንጻ ተማሪ',
  'semester_gpa': 'የስምስተር GPA',
  'upcoming_milestone': 'ቀጣይ ምልክት',
  'account_settings': 'የመለያ ቅንብሮች',
  'change_password': 'የይለፍ ቃል ቀይር',
  'notification_preferences': 'የማስታወቂያ ምርጫዎች',
  'course_updates': 'የኮርስ ማሻሻያዎች',
  'atelier_announcements': 'የአትሌ ማስታወቂያዎች',
  'offline_mode_demo': 'ከመስመር ውጭ ሁኔታ (Demo)',
  'logout': 'ውጣ',
  'dashboard': 'ዳሽቦርድ',
  'create_assignment': 'ተግባር ፍጠር',
  'recent_submissions': 'ቅርብ ማስገባቶች',
  'lecturer_dashboard_subtitle': 'በሶስት ንቁ ስርዓቶች ላይ የአእምሮ ጥራትን እናበረታታለን።',
  'active_courses': 'ንቁ ኮርሶች',
  'pending_feedback': 'በመጠበቅ ላይ ግምገማ',
  'pending_grading': 'በመለኪያ ላይ ያለ',
  'avg_feedback_time': 'አማካይ የግምገማ ጊዜ',
  'architecture_studio': 'የአርክቴክቸር ስቱዲዮ',
  'urban_morphology': 'የከተማ አቀማመጥ',
  'feedback_waiting': '{count} ስራዎች ግምገማን በመጠበቅ ላይ',
  'critiques_due': '{count} የስቱዲዮ ግምገማዎች ይጠበቃሉ',
  'grading_pending': '{count} ስራዎች ውጤት በመጠበቅ ላይ',
  'rubric_review': '{count} የመለኪያ ምርመራዎች ቀርተዋል',
  'avg_feedback_detail': 'አማካይ የግምገማ ጊዜ፡ {value} ቀናት',
  'fastest_turnaround': 'ፈጣን ምላሽ፡ {value} ቀናት',
  'slowest_turnaround': 'ዘገይ ምላሽ፡ {value} ቀናት',
  'tap_for_details': 'ለዝርዝር ይንኩ',
  'learning_signal': 'የመማር ምልክት',
  'focus_sessions': 'የትኩረት ስብሰባዎች',
  'analytics_signal_subtitle': 'በቅርብ ጊዜ ስብሰባዎች ላይ የተመሰረተ የማዕበል መጠን።',
  'this_week': 'በዚህ ሳምንት',
  'flow_score': 'የፍሰት ውጤት',
  'teaching_signal': 'የማስተማር ምልክት',
  'class_pulse': 'የክፍል ትርጉም',
  'analytics_signal_lecturer_subtitle': 'በንቁ ስቱዲዮዎች ላይ የተዋሃደ የኮርስ እንቅስቃሴ።',
  'on_time': 'በሰዓቱ',
  'avg_grade': 'አማካይ ውጤት',
  'feedback_speed': 'የግምገማ ፍጥነት',
  'meeting_logs': 'የስብሰባ ምዝግቦች',
  'attendance_dashboard': 'የተሳትፎ መቆጣጠሪያ',
  'attendance_dashboard_subtitle': 'በቡድኖች ላይ የቀጥታ ስብሰባ እና ተሳትፎ ይቆጣጠሩ።',
  'meeting_logs_unavailable': 'የስብሰባ ምዝግቦች አሁን አልተገኙም።',
  'no_meeting_logs': 'እስካሁን የተመዘገቡ ስብሰባዎች የሉም።',
  'total_sessions': 'አጠቃላይ ስብሰባዎች',
  'total_attendees': 'አጠቃላይ ተሳታፊዎች',
  'avg_session_duration': 'አማካይ የስብሰባ ጊዜ',
  'group_id_label': 'ቡድን {id}',
  'meeting_room_label': 'ክፍል {room}',
  'attendees_count': '{count} ተሳታፊዎች',
  'avg_duration_label': 'አማካይ {value}',
  'session_started_at': 'ጀመረ {time}',
  'meeting_oversight': 'የስብሰባ እይታ',
  'meeting_oversight_subtitle': 'ተሳትፎ፣ ጊዜ እና ተግባራዊነት ይመልከቱ።',
  'view_logs': 'ምዝግቦችን ይመልከቱ',
  'live_badge': 'ቀጥታ',
  'session_details': 'የስብሰባ ዝርዝሮች',
  'session_duration': 'የስብሰባ ጊዜ',
  'attendance_log': 'የተሳትፎ ምዝግብ',
  'participation_score': '{value}%',
  'member': 'አባል',
  'active_call_badge': '{count} ቀጥታ',
  'export_csv': 'CSV አውጣ',
  'export_csv_hint': 'ለሪፖርት የተሳትፎ ምዝግብ CSV ይፍጠሩ።',
  'copy_csv_hint': 'የሚከተለውን CSV ቅጂ አድርጉ።',
  'days': 'ቀናት',
  'faculty_profile': 'የአስተማሪ መገለጫ',
  'manage_teaching_preferences': 'የትምህርት ምርጫዎችን ያቀናብሩ።',
  'senior_faculty': 'ከፍተኛ አስተማሪ',
  'course_management': 'የኮርስ አስተዳደር',
  'active_courses_label': 'ንቁ ኮርሶች',
  'groups_assigned': 'የቡድን መደበኛ',
  'students': 'ተማሪዎች',
  'grading_preferences': 'የማስመዝገብ ምርጫዎች',
  'rubrics': 'መመዘኛዎች',
  'feedback_templates': 'የግምገማ አብነቶች',
  'final_thesis_proposal': 'የመጨረሻ ጥናት ፕሮፖዛል',
  'last_updated_months': 'ከ{count} ወራት በፊት ተዘምኗል',
  'course_updates_subtitle': 'አዲስ ትምህርት እና የተግባር ለውጦች',
  'atelier_announcements_subtitle': 'የስቱዲዮ ሙሉ ዜናና ክስተቶች',
};
